def prompt_gen(country_name, city_name, education_level) -> str:
    """
    Args:
        country_name (str): Country name
        city_name (str): City name
        education_level (str): e.g. "primary", "secondary", "tertiary"
    
    Returns:
        str: Prompt for deep research
    """

    prompt_text = f"""
        You are an education policy researcher specializing in school choice and student assignment systems.
        Your task is to research the **admission and assignment system** for **{education_level} education** in **{city_name}, {country_name}**.
        Focus on whether the city operates a **Coordinated Choice and Assignment System (CCAS)**.
        Focus on gathering the **most recent** and credible information available.

        ### Key Definitions
        A system is **Coordinated** if ALL of the following conditions hold: 1. Applicants submit a ranked list of preferences. 2. A group of institutions have enrollment partially or fully determined by an external authority. 3. Each applicant receives a single offer generated by a centralized algorithm. Otherwise, classify it as **Uncoordinated**.
        Preference List Length: The maximum number of institutions an applicant can rank in their preference list. If there is no explicit limit or there does not exist any preference list, return "Unknown".
        Priority Criteria: The factors considered in assigning students to institutions (e.g., academic performance, distance, socioeconomic equity...).
        Assignment Mechanism: The algorithm used to match students to institutions (e.g., Immediate Acceptance, Deferred Acceptance, Serial Dictatorship, Top Trading Cycles).
        Adoption Year: The year in which the first Coordinated Choice and Assignment System (CCAS) was implemented in the city. If no CCAS exists or no information is available, return "Unknown".
        Reform Year: The year in which the most recent major reform on CCAS was implemented. If no reforms have occurred since adoption, return the adoption year.

        ## Definitions and Abbreviations of Priority Criteria:
            - "academic": Academic performance of the student
            - "distance": Transportation or distance to school
            - "family": Parental employment or parental needs
            - "sen": Special educational needs
            - "gender": Gender equity
            - "ses": Socioeconomic equity
            - "sibling": Sibling priority
            - "diversity": Diversity quota
            - "zone": Zone or neighborhood priority
            - "rural": Rural area
            - "religion": Religious priority
            - "race": Racial or Indigenous quota
            - "alumni": Former student in the institution
            - "incumbent": Currently enrolled student
            - "population": Population-based criteria
            - "field": Specific field study
            - "gifted": Gifted applicants
            - "time": Waiting time

        ## Definitions of Assignment Mechanisms
            - "Immediate Acceptance": Also known as Boston Mechanism; applicants are assigned to their highest-ranked institution with available seats in a single round.
            - "Deferred Acceptance": Applicants are tentatively assigned to institutions based on their preferences and institution priorities, with reassignments occurring until a stable match is reached.
            - "Serial Dictatorship": Applicants are ordered (e.g., by lottery or priority), and each applicant selects their most preferred institution with available seats in turn.
            - "Top Trading Cycles": Applicants and institutions form cycles based on preferences and priorities, allowing for mutually beneficial exchanges until all applicants are assigned.

        # For each attributes, provide the link to the source of information (e.g., government policy document, academic research, credible news report) in the notes field. If multiple sources are used, summarize the key points and provide links to all sources.


        ### Required Output (JSON only)
        Return a single JSON object with the following fields:
            {{
            "ccas_status": "Coordinated | Uncoordinated | Unknown",
            "ccas_status_source": URL or citation of the source for ccas_status,
            "participating_institutions": "Public | Private | Both | Unknown",
            "participating_institutions_source": URL or citation of the source for participating_institutions,
            "preference_list_length": Number or "Unknown",
            "preference_list_length_source": URL or citation of the source for preference_list_length,
            "priority_criteria": ["academic", "distance", "family", "sen", "gender", "ses", "sibling", "diversity", "zone", "rural", "religion", "race", "alumni", "incumbent", "population", "field", "gifted", "time", "other", "Unknown"],
            "priority_criteria_source": URL or citation of the source for priority_criteria,
            "assignment_mechanism": "Immediate Acceptance | Deferred Acceptance | Serial Dictatorship | Top Trading Cycles | Other | Unknown",
            "assignment_mechanism_source": URL or citation of the source for assignment_mechanism,
            "adoption_year": Number or "Unknown",
            "adoption_year_source": URL or citation of the source for adoption_year,
            "reform_year": Number or "Unknown",
            "reform_year_source": URL or citation of the source for reform_year,
            "notes": "A brief description (< 250 words) of the admission and assignment system in the city, plus any additional relevant information."
        }}

        ## Rules:
            - If there does not exist a coordinated choice and assignment system, set ccas_status to "Uncoordinated" and other fields to "Unknown", and provide a brief explanation in notes.
            - Base answers on **credible public information** (laws, government portals, academic research, relatively credible news reports).
            - If city-level rules differ from national or regional rules, prioritize **city-level policy**.
            - If city-level information is unavailable, try to use the **most relevant higher-level policy** (e.g., national, provincial, or regional policy), and provide explanations in the notes.
            - If multiple systems exist (e.g., coordinated public schools vs. uncoordinated private schools), focus on the **coordinated system**, and provide explanations in the notes.
            - If different admission systems exist in different levels of secondary education (e.g. coordinated junior high vs. uncoordinated senior high), focus on the **coordinated system**, and provide explanations in the notes.
            - If information is missing or ambiguous, use "Unknown" explicitly.
            - Do NOT invent facts. If no credible information is found, return "Unknown" for the unknown fields.
            - Output **valid JSON only**, no markdown, no commentary.
        """
    return prompt_text