# -------------------------------------- #
# Project:          CCAS
# Objective:        OpenAI Functions

# Creator:          Tamara Munoz Ojeda
# Last Editor:      Tamara Munoz Ojeda

# Created:          21/11/2024
# Last Modified:    17/08/2025
# -------------------------------------- # 

# The object of this file is to define functions that call different OpenAI models. They are fairly standard code and specify the model, message, roles, output, and creativity of each model. They are the following:  
# 'apply_gpt4': calls the gpt-4o model 
# 'apply_gpt4mini': calls the gpt-4o mini model 
# 'apply_gpt5mini': calls the gpt-5 mini model 

# Importing necessary packages
from openai import OpenAI

# -------------------------------------- # 
def apply_gpt4(client, text, prompt, temp = 0.2):
    """
    Utilizes the OpenAI API to process text with a given prompt using gpt-4.

    Args:
        client (OpenAI): OpenAI API client initialized with the API key.
        text (str): The input text to be analyzed.
        prompt (str): The system prompt providing instructions.
        temp (float, optional): The sampling temperature for the response (creativity of answers). Values range from 0.0 (deterministic) to 1.0 (more random). Default is set to 0.2.

    Returns:
        str: The response content generated by model.
    """
    try:
        # Setting up the OpenAI message format
        messages = [
            {"role": "system", "content": prompt},  
            {"role": "user", "content": text}
        ]
        response = client.chat.completions.create(
            model = "gpt-4o",
            messages = messages,
            temperature = temp
        )
        # Obtaining response from OpenAI
        return response.choices[0].message.content
    except Exception as e:
        print(f"Error when processing text with gpt-4o: {e}")
        return text  # Returns the original text in case of error



# -------------------------------------- #
def apply_gpt4mini(client, text, prompt, temp = 0.2):
    """
    Utilizes the OpenAI API to process text with a given prompt using gpt-4o-mini.

    Args:
        client (OpenAI): OpenAI API client initialized with the API key.
        text (str): The input text to be analyzed.
        prompt (str): The system prompt providing instructions.
        temp (float, optional): The sampling temperature for the response (creativity of answers). Values range from 0.0 (deterministic) to 1.0 (more random). Default is set to 0.2.

    Returns:
        str: The response content generated by model.
    """
    try:
        # Setting up the OpenAI message format
        messages = [
            {"role": "system", "content": prompt},  
            {"role": "user", "content": text}
        ]
        response = client.chat.completions.create(
            model = "gpt-4o-mini",
            messages = messages,
            temperature = temp
        )
        # Obtaining response from OpenAI
        return response.choices[0].message.content
    except Exception as e:
        print(f"Error when processing text with gpt-4o-mini: {e}")
        return text  # Gives back original text in case of error
    

# -------------------------------------- #
def apply_gpt5mini(client, text, prompt, temp = 0.2):
    """
    Utilizes the OpenAI API to process text with a given prompt using gpt-5-mini.

    Args:
        client (OpenAI): OpenAI API client initialized with the API key.
        text (str): The input text to be analyzed.
        prompt (str): The system prompt providing instructions.
        temp (float, optional): The sampling temperature for the response (creativity of answers). Values range from 0.0 (deterministic) to 1.0 (more random). Default is set to 0.2.

    Returns:
        str: The response content generated by model.
    """
    try:
        # Setting up the OpenAI message format
        messages = [
            {"role": "system", "content": prompt},  
            {"role": "user", "content": text}
        ]
        response = client.chat.completions.create(
            model = "gpt-5-mini",
            messages = messages,
            temperature = temp
        )
        # Obtaining response from OpenAI
        return response.choices[0].message.content
    except Exception as e:
        print(f"Error when processing text with gpt-5-mini: {e}")
        return text  # Gives back original text in case of error   