# -------------------------------------- #
# Project:          CCAS
# Objective:        OpenAI Functions

# Creator:          Tamara Munoz Ojeda
# Last Editor:      Tamara Munoz Ojeda

# Created:          21/11/2024
# Last Modified:    17/08/2025
# -------------------------------------- # 

# The object of this file is to define functions that call different OpenAI models. They are fairly standard code and specify the model, message, roles, output, and creativity of each model. They are the following:  
# 'apply_gpt4': calls the gpt-4o model 
# 'apply_gpt4mini': calls the gpt-4o mini model 
# 'apply_gpt5mini': calls the gpt-5 mini model 

# Importing necessary packages
from openai import OpenAI

# -------------------------------------- #
def generate_ccas_extraction_prompt() -> str:
    """
    Generate a prompt for extracting centralized admission and assignment system information from academic papers.
    Designed to handle multiple regions/cities mentioned in a paper and gracefully handle missing or incomplete information.
    
    Returns:
        str: System prompt for CCAS extraction from academic papers
    """
    
    prompt_text = """
You are an education policy researcher specializing in school choice and student assignment systems.
Your task is to extract information about **centralized admission and assignment systems** from the provided academic paper text.
The paper may discuss multiple cities, administrative regions, or countries, or may contain no relevant information.

### Key Definitions
A system is **Coordinated** if ALL of the following conditions hold:
1. Applicants submit a ranked list of preferences
2. A group of institutions have enrollment partially or fully determined by an external authority
3. Each applicant receives a single offer generated by a centralized algorithm
Otherwise, classify it as **Uncoordinated**.

### Attributes to Extract (for each region/city mentioned):

- **CCAS Status**: Whether the region operates a Coordinated Choice and Assignment System. Values: Coordinated, Uncoordinated, or Unknown.
- **ISO3 Country Code**: Three-letter ISO 3166-1 alpha-3 country code (e.g., "SGP" for Singapore, "CHN" for China).
- **Education Level**: The level of education covered by the system. Choose ONE: primary, secondary, or tertiary. If the paper discusses multiple education levels, create separate JSON objects for each level.
- **Preference List Length**: The maximum number of institutions an applicant can rank. If no limit exists or no preference list is mentioned, return "Unknown".
- **Priority Criteria**: Factors considered in assigning students (e.g., academic performance, distance, socioeconomic equity). See abbreviations below.
- **Assignment Mechanism**: Algorithm used to match students (e.g., Immediate Acceptance, Deferred Acceptance, Serial Dictatorship, Top Trading Cycles).
- **Adoption Year**: Year the first CCAS was implemented. Return "Unknown" if not mentioned.
- **Reform Year**: Year of most recent major CCAS reform. Return adoption year if no reforms mentioned.

### Priority Criteria Abbreviations:
- "academic": Academic performance
- "distance": Transportation or distance to school
- "family": Parental employment or parental needs
- "sen": Special educational needs
- "gender": Gender equity
- "ses": Socioeconomic equity
- "sibling": Sibling priority
- "diversity": Diversity quota
- "zone": Zone or neighborhood priority
- "rural": Rural area
- "religion": Religious priority
- "race": Racial or Indigenous quota
- "alumni": Former student in institution
- "incumbent": Currently enrolled student
- "population": Population-based criteria
- "field": Specific field study
- "gifted": Gifted applicants
- "time": Waiting time
- "other": Other criteria not listed above
- "Unknown": No criteria mentioned

### Assignment Mechanisms:
- "Immediate Acceptance": Boston Mechanism; single round assignment
- "Deferred Acceptance": Tentative assignment with reassignments until stable match
- "Serial Dictatorship": Ordered applicants select in turn
- "Top Trading Cycles": Cycle-based exchanges until all assigned
- "Other": Any other mechanism not listed above
- "Unknown": Not specified

### Output Format (JSON only)

Return a JSON object (or array of objects if multiple regions/education levels are discussed) with fields:
{
    "region": "City, Region, or Country name (or 'Not specified' if unclear)",
    "iso3_country_code": "Three-letter ISO 3166-1 alpha-3 code (e.g., 'SGP', 'CHN', 'Unknown')",
    "education_level": "primary | secondary | tertiary | Unknown",
    "ccas_status": "Coordinated | Uncoordinated | Unknown",
    "participating_institutions": "Public | Private | Both | Unknown",
    "preference_list_length": "Number or Unknown",
    "priority_criteria": ["list of criteria codes"],
    "assignment_mechanism": "Mechanism or Unknown",
    "adoption_year": "Number or Unknown",
    "reform_year": "Number or Unknown",
    "notes": "Summary (< 250 words) of the admission system description, caveats, or data quality issues"
}

### Rules:
- **Multiple regions and education levels**: If the paper discusses multiple cities/regions or multiple education levels, return an array of JSON objects. Each object represents ONE region-education_level combination.
- **Education level per object**: Each JSON object must have only ONE education_level value (primary, secondary, or tertiary). If a paper discusses primary AND secondary education for the same region, return two separate JSON objects.
- **CCAS status cascade**: If ccas_status is "Uncoordinated" or "Unknown", set ALL following fields to "Unknown" (except notes): participating_institutions, preference_list_length, priority_criteria, assignment_mechanism, adoption_year, reform_year. Only notes should contain an explanation.
- **Coordinated vs. Uncoordinated**: If no coordinated system is mentioned for a region, set ccas_status to "Uncoordinated" (unless explicitly stated differently).
- **Unknown vs. Absent**: Use "Unknown" only when the paper DISCUSSES the system but information is incomplete.
- **Do NOT invent facts**: If no credible information is found in the paper, return "Unknown" and explain in notes.
- **Priority Criteria**: Return an array. If multiple criteria are mentioned, include all. If none mentioned, return ["Unknown"].
- **Error handling**: If the paper does not discuss admission systems at all, return a single JSON object with all fields set to "Unknown" and notes explaining no relevant information was found.
- **Output valid JSON only**: No markdown, no commentary, just JSON.

### Example Output Structure:
[
    {
        "region": "Singapore",
        "iso3_country_code": "SGP",
        "education_level": "secondary",
        "ccas_status": "Coordinated",
        "participating_institutions": "Public",
        "preference_list_length": 6,
        "priority_criteria": ["academic", "distance", "zone"],
        "assignment_mechanism": "Deferred Acceptance",
        "adoption_year": 1998,
        "reform_year": 2014,
        "notes": "Singapore's Integrated Result Slip system uses deferred acceptance..."
    },
    {
        "region": "Singapore",
        "iso3_country_code": "SGP",
        "education_level": "primary",
        "ccas_status": "Uncoordinated",
        "participating_institutions": "Unknown",
        "preference_list_length": "Unknown",
        "priority_criteria": ["Unknown"],
        "assignment_mechanism": "Unknown",
        "adoption_year": "Unknown",
        "reform_year": "Unknown",
        "notes": "Primary education admissions are handled locally by schools without central coordination."
    }
]
"""
    return prompt_text


# -------------------------------------- # 
def apply_gpt4(client, text, prompt, temp = 0.2):
    """
    Utilizes the OpenAI API to process text with a given prompt using gpt-4.

    Args:
        client (OpenAI): OpenAI API client initialized with the API key.
        text (str): The input text to be analyzed.
        prompt (str): The system prompt providing instructions.
        temp (float, optional): The sampling temperature for the response (creativity of answers). Values range from 0.0 (deterministic) to 1.0 (more random). Default is set to 0.2.

    Returns:
        str: The response content generated by model.
    """
    try:
        # Setting up the OpenAI message format
        messages = [
            {"role": "system", "content": prompt},  
            {"role": "user", "content": text}
        ]
        response = client.chat.completions.create(
            model = "gpt-4o",
            messages = messages,
            temperature = temp
        )
        # Obtaining response from OpenAI
        return response.choices[0].message.content
    except Exception as e:
        print(f"Error when processing text with gpt-4o: {e}")
        return text  # Returns the original text in case of error



# -------------------------------------- #
def apply_gpt4mini(client, text, prompt, temp = 0.2):
    """
    Utilizes the OpenAI API to process text with a given prompt using gpt-4o-mini.

    Args:
        client (OpenAI): OpenAI API client initialized with the API key.
        text (str): The input text to be analyzed.
        prompt (str): The system prompt providing instructions.
        temp (float, optional): The sampling temperature for the response (creativity of answers). Values range from 0.0 (deterministic) to 1.0 (more random). Default is set to 0.2.

    Returns:
        str: The response content generated by model.
    """
    try:
        # Setting up the OpenAI message format
        messages = [
            {"role": "system", "content": prompt},  
            {"role": "user", "content": text}
        ]
        response = client.chat.completions.create(
            model = "gpt-4o-mini",
            messages = messages,
            temperature = temp
        )
        # Obtaining response from OpenAI
        return response.choices[0].message.content
    except Exception as e:
        print(f"Error when processing text with gpt-4o-mini: {e}")
        return text  # Gives back original text in case of error
    

# -------------------------------------- #
def apply_gpt5mini(client, text, prompt, temp = 0.2):
    """
    Utilizes the OpenAI API to process text with a given prompt using gpt-5-mini.

    Args:
        client (OpenAI): OpenAI API client initialized with the API key.
        text (str): The input text to be analyzed.
        prompt (str): The system prompt providing instructions.
        temp (float, optional): The sampling temperature for the response (creativity of answers). Values range from 0.0 (deterministic) to 1.0 (more random). Default is set to 0.2.

    Returns:
        str: The response content generated by model.
    """
    try:
        # Setting up the OpenAI message format
        messages = [
            {"role": "system", "content": prompt},  
            {"role": "user", "content": text}
        ]
        response = client.chat.completions.create(
            model = "gpt-5-mini",
            messages = messages,
            temperature = temp
        )
        # Obtaining response from OpenAI
        return response.choices[0].message.content
    except Exception as e:
        print(f"Error when processing text with gpt-5-mini: {e}")
        return text  # Gives back original text in case of error


# -------------------------------------- #
def extract_ccas_from_paper(client, paper_text, model="gpt-4o", temp=0.2):
    """
    Extract CCAS (Coordinated Choice and Assignment System) information from academic paper text.
    
    Designed to handle papers discussing multiple regions and gracefully handle missing information.
    
    Args:
        client (OpenAI): OpenAI API client initialized with the API key.
        paper_text (str): The academic paper text to analyze.
        model (str, optional): OpenAI model to use. Default is "gpt-4o".
        temp (float, optional): Temperature for response generation. Default is 0.2 (low randomness for structured output).
    
    Returns:
        str: JSON object(s) containing extracted CCAS information. Returns array if multiple regions found,
             single object if one region found, or error object if no relevant information found.
    """
    try:
        prompt = generate_ccas_extraction_prompt()
        messages = [
            {"role": "system", "content": prompt},  
            {"role": "user", "content": f"Extract CCAS information from this academic paper:\n\n{paper_text}"}
        ]
        response = client.chat.completions.create(
            model=model,
            messages=messages,
            temperature=temp
        )
        return response.choices[0].message.content
    except Exception as e:
        print(f"Error when extracting CCAS from paper with {model}: {e}")
        return '{"error": "Failed to extract CCAS information", "details": "' + str(e) + '"}'   